# Generated by Django 5.2.8 on 2025-11-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
